=== richardRadli/pill_detection/config/json_files/stream_net_config_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "StreamNet Configuration",
  "type": "object",
  "properties": {
    "dataset_type": {
      "type": "string",
      "enum": ["ogyeiv2", "cure_one_sided", "cure_two_sided"]
    },
    "type_of_net": {
      "type": "string",
      "enum": ["EfficientNetV2"]
    },
    "type_of_stream": {
      "type": "string",
      "enum": ["Contour", "LBP", "RGB", "Texture"]
    },
    "type_of_loss_func": {
      "type": "string",
      "enum": ["hmtl", "dmtl"]
    },
    "type_of_dmtl": {
      "type": "string",
      "enum": ["visual", "textual"]
    },
    "fold": {
      "type": "string",
      "enum": ["fold1", "fold2", "fold3", "fold4", "fold5"]
    },
    "networks": {
      "type": "object",
      "properties": {
        "EfficientNetV2": {
          "type": "object",
          "properties": {
            "learning_rate": { "type": "number" },
            "image_size": { "type": "integer" }
          }
        }
      }
    },
    "upper_norm_limit": {
      "type": "number"
    },
    "mining_type": {
      "type": "string",
      "enum": ["semihard", "hard", "easy"]
    },
    "margin": {
      "type": "number"
    },
    "epochs": {
      "type": "integer"
    },
    "batch_size": {
      "type": "integer"
    },
    "train_valid_ratio": {
      "type": "number"
    },
    "streams": {
      "type": "object",
      "properties": {
        "Contour": {
          "type": "object",
          "properties": {
            "channels": {
              "type": "array",
              "items": {
                "type": "number"
              }
            },
            "embedded_dim": {
              "type": "integer"
            },
            "grayscale": {
              "type": "boolean"
            }
          }
        },
        "LBP": {
          "type": "object",
          "properties": {
            "channels": {
              "type": "array",
              "items": {
                "type": "number"
              }
            },
            "embedded_dim": {
              "type": "integer"
            },
            "grayscale": {
              "type": "boolean"
            }
          }
        },
        "RGB": {
          "type": "object",
          "properties": {
            "channels": {
              "type": "array",
              "items": {
                "type": "number"
              }
            },
            "embedded_dim": {
              "type": "integer"
            },
            "grayscale": {
              "type": "boolean"
            }
          }
        },
        "Texture": {
          "type": "object",
          "properties": {
            "channels": {
              "type": "array",
              "items": {
                "type": "number"
              }
            },
            "embedded_dim": {
              "type": "integer"
            },
            "grayscale": {
              "type": "boolean"
            }
          }
        }
      }
    },
    "weight_decay": {
      "type": "number"
    },
    "step_size": {
      "type": "integer"
    },
    "gamma": {
      "type": "number"
    },
    "load_ref_vector": {
      "type": "boolean"
    }
  },
  "required": ["dataset_type", "type_of_net", "type_of_stream", "type_of_loss_func", "networks", "mining_type",
    "margin", "epochs", "batch_size", "train_valid_ratio", "weight_decay", "step_size", "gamma", "load_ref_vector",
    "streams"]
}

=== richardRadli/pill_detection/config/json_files/stream_net_config.json
{
  "dataset_type": "ogyeiv2",
  "type_of_net": "EfficientNetV2",
  "mining_type": "semihard",
  "type_of_stream": "Texture",
  "type_of_loss_func": "dmtl",
  "type_of_dmtl": "textual",
  "fold": "fold1",
  "margin": 0.2,
  "upper_norm_limit": 0.5,
  "epochs": 20,
  "batch_size": 32,
  "train_valid_ratio": 0.8,
  "weight_decay": 0.00001,
  "step_size": 5,
  "gamma": 0.333,
  "load_ref_vector": false,
  "networks": {
    "EfficientNetV2": {
      "learning_rate": 0.0001,
      "image_size": 224
    }
  },
  "streams": {
    "Contour": {
      "channels": [1, 32, 48, 64, 128, 192, 256],
      "embedded_dim": 128,
      "grayscale": true
    },
    "LBP": {
      "channels": [1, 32, 48, 64, 128, 192, 256],
      "embedded_dim": 128,
      "grayscale": true
    },
    "RGB": {
      "channels": [3, 64, 96, 128, 256, 384, 512],
      "embedded_dim": 256,
      "grayscale": false
    },
    "Texture": {
      "channels": [1, 32, 48, 64, 128, 192, 256],
      "embedded_dim": 128,
      "grayscale": true
    }
  }
}
